# Generated by Django 4.2.20 on 2025-03-20 11:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=255)),
                ('sinopse', models.TextField()),
                ('num_pag', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('capa', models.ImageField(blank=True, null=True, upload_to='livros/')),
                ('ano_publicacao', models.PositiveIntegerField(blank=True, null=True)),
                ('genero', models.CharField(choices=[('ficcao', 'Ficção'), ('romance', 'Romance'), ('terror', 'Terror'), ('fantasia', 'Fantasia'), ('suspense', 'Suspense'), ('ciencia', 'Ciência'), ('historia', 'História'), ('biografia', 'Biografia'), ('autoajuda', 'Autoajuda'), ('infantil', 'Infantil'), ('outro', 'Outro'), ('nenhum', 'Nenhum')], default='nenhum', max_length=50)),
                ('palavra_chave', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProgressoLeitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pag_atual', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('lido', models.BooleanField(default=False)),
                ('anotacao', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('inicio_leitura', models.DateTimeField(blank=True, null=True)),
                ('fim_leitura', models.DateTimeField(blank=True, null=True)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Biblioteca.livro')),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('utilizador', 'livro')},
            },
        ),
        migrations.CreateModel(
            name='Biblioteca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estante', models.CharField(choices=[('lido', 'Lido'), ('a ler', 'A Ler'), ('quero ler', 'Quero Ler'), ('abandonei', 'Abandonei'), ('outra', 'Outra')], default='quero ler', max_length=20)),
                ('data_adicao', models.DateTimeField(auto_now_add=True)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Biblioteca.livro')),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('utilizador', 'livro', 'estante')},
            },
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avaliacao', models.IntegerField(choices=[(1, '1 - Péssimo'), (2, '2 - Ruim'), (3, '3 - Médio'), (4, '4 - Bom'), (5, '5 - Excelente')])),
                ('comentario', models.TextField(blank=True, null=True)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='Biblioteca.livro')),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('utilizador', 'livro')},
            },
        ),
    ]
