# Generated by Django 4.2.20 on 2025-04-06 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Livros', '0001_initial'),
        ('Utilizadores', '0012_alter_utilizador_generos_fav'),
        ('Biblioteca', '0003_alter_livro_genero_delete_genero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recomendacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fonte', models.CharField(choices=[('ia', 'IA'), ('manual', 'Manual'), ('outro', 'Outro')], default='ia', max_length=10)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('data_recomendacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='livro',
            name='genero',
        ),
        migrations.RemoveConstraint(
            model_name='biblioteca',
            name='unique_livro_por_estante',
        ),
        migrations.AddField(
            model_name='biblioteca',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='livro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='Livros.livro'),
        ),
        migrations.AlterField(
            model_name='biblioteca',
            name='livro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Livros.livro'),
        ),
        migrations.AlterField(
            model_name='progressoleitura',
            name='livro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Livros.livro'),
        ),
        migrations.AddConstraint(
            model_name='biblioteca',
            constraint=models.UniqueConstraint(fields=('utilizador', 'livro'), name='unique_livro_na_biblioteca'),
        ),
        migrations.DeleteModel(
            name='Generos',
        ),
        migrations.DeleteModel(
            name='Livro',
        ),
        migrations.AddField(
            model_name='recomendacao',
            name='livro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Livros.livro'),
        ),
        migrations.AddField(
            model_name='recomendacao',
            name='recomendado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recomendacoes_feitas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recomendacao',
            name='utilizador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendacoes_recebidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='recomendacao',
            unique_together={('utilizador', 'livro')},
        ),
    ]
