# Generated by Django 4.2.20 on 2025-05-03 03:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Biblioteca', '0005_delete_avaliacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estantes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('nome', 'utilizador')},
            },
        ),
        migrations.AlterField(
            model_name='biblioteca',
            name='estante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livros', to='Biblioteca.estante'),
        ),
    ]
