# Generated by Django 4.2.20 on 2025-05-03 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteca', '0006_estante_alter_biblioteca_estante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biblioteca',
            name='estante',
        ),
        migrations.AddField(
            model_name='biblioteca',
            name='estante_customizada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Biblioteca.estante'),
        ),
    ]
