# Generated by Django 4.2.20 on 2025-03-20 11:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DesafioLeitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('meta', models.PositiveIntegerField(default=1)),
                ('participantes', models.ManyToManyField(blank=True, related_name='desafios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_inicio'],
            },
        ),
    ]
