# Generated by Django 4.2.20 on 2025-03-26 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Desafios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desafioleitura',
            name='data_inicio',
            field=models.DateField(auto_now_add=True),
        ),
    ]
