# Generated by Django 4.2.20 on 2025-03-26 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('ficcao', 'Ficção'), ('romance', 'Romance'), ('terror', 'Terror'), ('fantasia', 'Fantasia'), ('suspense', 'Suspense'), ('ciencia', 'Ciência'), ('historia', 'História'), ('biografia', 'Biografia'), ('autoajuda', 'Autoajuda'), ('infantil', 'Infantil'), ('outro', 'Outro'), ('nenhum', 'Nenhum')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Generos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('ficcao', 'Ficção'), ('romance', 'Romance'), ('terror', 'Terror'), ('fantasia', 'Fantasia'), ('suspense', 'Suspense'), ('ciencia', 'Ciência'), ('historia', 'História'), ('biografia', 'Biografia'), ('autoajuda', 'Autoajuda'), ('infantil', 'Infantil'), ('outro', 'Outro'), ('nenhum', 'Nenhum')], max_length=20, unique=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='avaliacao',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='biblioteca',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='progressoleitura',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='avaliacao',
            field=models.IntegerField(choices=[(1, '1 - Péssimo'), (2, '2 - Mau'), (3, '3 - Médio'), (4, '4 - Bom'), (5, '5 - Excelente')]),
        ),
        migrations.AddConstraint(
            model_name='avaliacao',
            constraint=models.UniqueConstraint(fields=('utilizador', 'livro'), name='unique_avaliacao'),
        ),
        migrations.AddConstraint(
            model_name='biblioteca',
            constraint=models.UniqueConstraint(fields=('utilizador', 'livro', 'estante'), name='unique_livro_por_estante'),
        ),
        migrations.AddConstraint(
            model_name='progressoleitura',
            constraint=models.UniqueConstraint(fields=('utilizador', 'livro'), name='unique_progresso_leitura'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='genero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livros', to='Biblioteca.genero'),
        ),
    ]
