# Generated by Django 4.2.20 on 2025-05-07 12:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Livros', '0004_alter_avaliacao_avaliacao_avaliacaoapi'),
        ('Biblioteca', '0007_remove_biblioteca_estante_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='biblioteca',
            name='unique_livro_na_biblioteca',
        ),
        migrations.AlterUniqueTogether(
            name='biblioteca',
            unique_together={('utilizador', 'livro', 'estante_customizada')},
        ),
    ]
