# Generated by Django 4.2.20 on 2025-05-07 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteca', '0008_remove_biblioteca_unique_livro_na_biblioteca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estante',
            name='cor',
            field=models.CharField(default='#FFE4EC', max_length=7),
        ),
    ]
