# Generated by Django 4.2.20 on 2025-05-12 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteca', '0015_alter_estante_cor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progressoleitura',
            name='lido',
        ),
    ]
