# Generated by Django 4.2.20 on 2025-05-13 01:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Livros', '0005_livro_google_id'),
        ('Biblioteca', '0016_remove_progressoleitura_lido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressoleitura',
            name='pag_atual',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='LeituraDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('paginas_lidas', models.PositiveIntegerField()),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Livros.livro')),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('utilizador', 'livro', 'data')},
            },
        ),
    ]
