# Generated by Django 4.2.20 on 2025-05-13 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteca', '0017_alter_progressoleitura_pag_atual_leituradiaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leituradiaria',
            name='data',
            field=models.DateField(),
        ),
    ]
