# Generated by Django 4.2.20 on 2025-03-27 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Utilizadores', '0002_remove_utilizador_palavra_passe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilizador',
            name='username',
        ),
    ]
