# Generated by Django 4.2.20 on 2025-03-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utilizadores', '0003_remove_utilizador_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilizador',
            name='username',
            field=models.CharField(default='default_user', max_length=100, unique=True),
        ),
    ]
