# Generated by Django 4.2.20 on 2025-03-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utilizadores', '0005_alter_utilizador_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilizador',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
