# Generated by Django 4.2.20 on 2025-04-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utilizadores', '0009_alter_utilizador_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilizador',
            name='nome',
        ),
        migrations.AlterField(
            model_name='utilizador',
            name='username',
            field=models.CharField(default='user_default', max_length=100, unique=True),
        ),
    ]
