# Generated by Django 4.2.20 on 2025-04-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utilizadores', '0010_remove_utilizador_nome_alter_utilizador_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilizador',
            name='nome',
            field=models.CharField(default='Utilizador', max_length=100),
        ),
        migrations.AlterField(
            model_name='utilizador',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
