# Generated by Django 4.2.20 on 2025-04-06 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Livros', '0001_initial'),
        ('Utilizadores', '0011_utilizador_nome_alter_utilizador_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilizador',
            name='generos_fav',
            field=models.ManyToManyField(blank=True, related_name='utilizadores', to='Livros.generos'),
        ),
    ]
