# Generated by Django 4.2.20 on 2025-04-06 22:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Editora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FonteLivro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('referencia_api', models.CharField(blank=True, max_length=255, null=True)),
                ('data_importacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Generos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('ficcao', 'Ficção'), ('romance', 'Romance'), ('terror', 'Terror'), ('fantasia', 'Fantasia'), ('suspense', 'Suspense'), ('ciencia', 'Ciência'), ('historia', 'História'), ('biografia', 'Biografia'), ('autoajuda', 'Autoajuda'), ('infantil', 'Infantil'), ('outro', 'Outro'), ('nenhum', 'Nenhum')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=255)),
                ('sinopse', models.TextField()),
                ('num_pag', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('capa', models.ImageField(blank=True, null=True, upload_to='livros/')),
                ('ano_publicacao', models.PositiveIntegerField(blank=True, null=True)),
                ('palavra_chave', models.TextField(blank=True, null=True)),
                ('isbn', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('editora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livros', to='Livros.editora')),
                ('fonte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Livros.fontelivro')),
                ('genero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livros', to='Livros.generos')),
                ('idioma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Livros.idioma')),
            ],
        ),
    ]
