# Generated by Django 4.2.20 on 2025-04-22 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Livros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PalavraChave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='livro',
            name='fonte',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='genero',
        ),
        migrations.AddField(
            model_name='livro',
            name='generos',
            field=models.ManyToManyField(related_name='livros', to='Livros.generos'),
        ),
        migrations.AlterField(
            model_name='generos',
            name='nome',
            field=models.CharField(choices=[('ficcao', 'Ficção'), ('romance', 'Romance'), ('terror', 'Terror'), ('fantasia', 'Fantasia'), ('suspense', 'Suspense'), ('ciencia', 'Ciência'), ('historia', 'História'), ('biografia', 'Biografia'), ('autoajuda', 'Autoajuda'), ('infantil', 'Infantil'), ('classico', 'Clássico'), ('outro', 'Outro'), ('nenhum', 'Nenhum')], max_length=20, unique=True),
        ),
        migrations.RemoveField(
            model_name='livro',
            name='palavra_chave',
        ),
        migrations.AddField(
            model_name='livro',
            name='palavra_chave',
            field=models.ManyToManyField(blank=True, related_name='livros', to='Livros.palavrachave'),
        ),
    ]
