# Generated by Django 4.2.20 on 2025-05-07 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Livros', '0004_alter_avaliacao_avaliacao_avaliacaoapi'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='google_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
