# Generated by Django 4.2.20 on 2025-05-22 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Livros', '0005_livro_google_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('quero_ler', 'Quero Ler'), ('a_ler', 'A Ler'), ('lido', 'Lido'), ('abandonado', 'Abandonado')], default='quero_ler', max_length=15)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('anotacoes', models.TextField(blank=True, null=True)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leituras', to='Livros.livro')),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leituras', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('utilizador', 'livro')},
            },
        ),
    ]
