# Generated by Django 4.2.20 on 2025-06-02 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Livros', '0006_leitura'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacaoapi',
            name='autor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='avaliacaoapi',
            name='capa_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avaliacaoapi',
            name='titulo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
