# Generated by Django 4.2.20 on 2025-06-13 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Livros', '0007_avaliacaoapi_autor_avaliacaoapi_capa_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='ano_publicacao',
            field=models.PositiveIntegerField(default=2025),
        ),
    ]
