# Generated by Django 4.2.20 on 2025-06-13 22:14

from django.db import migrations, models
import nookbook.apps.Livros.models


class Migration(migrations.Migration):

    dependencies = [
        ('Livros', '0008_alter_livro_ano_publicacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='ano_publicacao',
            field=models.PositiveIntegerField(default=nookbook.apps.Livros.models.ano_atual),
        ),
    ]
