# Generated by Django 4.2.20 on 2025-06-15 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Livros', '0010_leitura_avaliacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='capa',
            field=models.ImageField(blank=True, default='capas/capa_default.png', null=True, upload_to='capas/'),
        ),
    ]
