# Generated by Django 4.2.20 on 2025-06-15 17:00

from django.db import migrations, models
import nookbook.apps.Livros.models


class Migration(migrations.Migration):

    dependencies = [
        ('Livros', '0011_alter_livro_capa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='ano_publicacao',
            field=models.PositiveIntegerField(blank=True, default=nookbook.apps.Livros.models.ano_atual, null=True),
        ),
    ]
