# Generated by Django 4.2.20 on 2025-06-15 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Livros', '0012_alter_livro_ano_publicacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='ano_publicacao',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
