# Generated by Django 4.2.20 on 2025-03-26 17:09

import nookbook.apps.Utilizadores.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteca', '0002_genero_generos_alter_avaliacao_unique_together_and_more'),
        ('Utilizadores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilizador',
            name='palavra_passe',
        ),
        migrations.AlterField(
            model_name='utilizador',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to=nookbook.apps.Utilizadores.models.user_directory_path),
        ),
        migrations.RemoveField(
            model_name='utilizador',
            name='generos_fav',
        ),
        migrations.AddField(
            model_name='utilizador',
            name='generos_fav',
            field=models.ManyToManyField(blank=True, related_name='utilizadores', to='Biblioteca.generos'),
        ),
    ]
