# Generated by Django 4.2.20 on 2025-03-27 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Utilizadores', '0008_alter_utilizador_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='utilizador',
            managers=[
            ],
        ),
    ]
